# Generated by Django 5.0.6 on 2024-09-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_job_is_actual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя компании')),
                ('website', models.URLField(verbose_name='Сайт компании')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Логотип компании')),
            ],
        ),
    ]
